export const PLANS = {
  free: {
    name: "Free",
    maxHotels: 1,
    maxActiveBookings: 10,
    allowedHotelFields: ["name", "address", "phone", "location"],
    allowedBookingFields: ["checkin", "checkout", "client"],
    allowCustomFields: false,
    allowFileUploads: false,
    allowDigitalSignatures: false,
    reports: "basic",
    integrations: ["calendar"],
    /** Cantidad máxima de huespedes por reserva */
    maxPaxPerBooking: 4,
  },
  pro: {
    name: "Pro",
    maxHotels: 3,
    maxActiveBookings: 100,
    allowedHotelFields: "all",
    allowedBookingFields: "all",
    allowCustomFields: true,
    allowFileUploads: true,
    allowDigitalSignatures: true,
    reports: "advanced",
    integrations: ["calendar", "pms"],
    maxPaxPerBooking: 7,
  },
  business: {
    name: "Business",
    maxHotels: 20,
    maxActiveBookings: 999,
    allowedHotelFields: "all",
    allowedBookingFields: "all",
    allowCustomFields: true,
    allowFileUploads: true,
    allowDigitalSignatures: true,
    reports: "full",
    integrations: ["calendar", "pms", "externalPayments"],
    maxPaxPerBooking: 999,
  },
}
